version: '3.5'

services:
  user-cli:
    build: ./cli
    container_name: x-user-cli

  user-service:
    build: ./ser
    container_name: x-user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres_password"

  database:
    restart: always # ensures the container will restart on crash
    image: postgres
    container_name: x-postgres
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres_password
